/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/Token/*')
global class TokenService {
    global TokenService() {

    }
    @HttpGet
    global static void doGet() {

    }
    @HttpPost
    global static void doPost(List<et4ae5.TokenService.TokenServiceRequest> tokenReqs) {

    }
global class TokenServiceRequest {
    global TokenServiceRequest() {

    }
}
}
