/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class jsButtonMethods {
    global jsButtonMethods() {

    }
    webService static String activateTriggeredSend(String trigSendId) {
        return null;
    }
    webService static String getPACId(String acctId) {
        return null;
    }
    webService static Boolean isETIntegrated() {
        return null;
    }
    webService static String namespace() {
        return null;
    }
    webService static String pauseTriggeredSend(String trigSendId) {
        return null;
    }
    webService static String performResub(String subKey, String objectType) {
        return null;
    }
    webService static String performUnsub(String subKey, String objectType) {
        return null;
    }
    webService static void resetConfiguration() {

    }
    webService static String saveRemember(et4ae5.jsButtonMethods.rememberParams params) {
        return null;
    }
global class rememberParams {
    @WebService
    webService String isChecked;
    @WebService
    webService String url;
    @WebService
    webService String userId;
    global rememberParams() {

    }
}
}
