/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class SupportUtilities {
    global SupportUtilities() {

    }
    @Deprecated
    global static Boolean areFuelRoutesEnabled() {
        return null;
    }
    global static void deleteJwtSettings(String user) {

    }
    global static void deleteUserTokens(String customSettingKey) {

    }
    global static void deleteUserTokens(Id userId, Boolean deleteBUSpecificTokens) {

    }
    global static void deleteUserTokens(Id userId, String MID) {

    }
    global static Integer getJWTEnablementValue() {
        return null;
    }
    global static void resetConfiguration() {

    }
}
