/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class JBintFireBulkEvent {
    global JBintFireBulkEvent() {

    }
    @InvocableMethod(label='Fire Bulk JB Event' description='Fires off a bulk event for the given set of params')
    global static void fireBulkEvent(List<et4ae5.JBIntFireEventParams> fireEventParamList) {

    }
}
