/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class JBIntFireEventParams {
    @InvocableVariable( required=true)
    global String ContactKey;
    @InvocableVariable( required=true)
    global String ContactPersonType;
    @InvocableVariable( required=true)
    global String EventDataConfig;
    @InvocableVariable( required=true)
    global String EventDefinitionKey;
    @InvocableVariable( required=false)
    global String EventType;
    @InvocableVariable( required=true)
    global String OwnerMID;
    @InvocableVariable( required=true)
    global String SalesforceObjectId;
    @InvocableVariable( required=true)
    global String SalesforceObjectName;
    @InvocableVariable( required=true)
    global String VersionNumber;
    global JBIntFireEventParams() {

    }
}
