/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class mockHttpResponseGenerator implements System.HttpCalloutMock {
    global Boolean errored;
    global String myBody;
    global String status;
    global Integer statusCode;
    global mockHttpResponseGenerator() {

    }
    global mockHttpResponseGenerator(String bodyString) {

    }
    global System.HttpResponse respond(System.HttpRequest req) {
        return null;
    }
}
