/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class trackingWebServices {
    global trackingWebServices() {

    }
    webService static String buttonResponse(String sendDefId) {
        return null;
    }
    webService static void cancelSendDef(String sendDefId) {

    }
    webService static void cancelSmsDef(String smsDefId) {

    }
    webService static void immediateTracking(String sendDefId, String evalString) {

    }
    webService static String requestImmediateTracking(String sendDefId) {
        return null;
    }
    webService static Boolean requestTracking(String sendDefId, String evalString) {
        return null;
    }
}
