/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class DownloadTrailIcons implements Database.AllowsCallouts, Database.Batchable<SObject>, Database.Stateful {
    global void execute(Database.BatchableContext bc, List<trailheadapp__Trail__c> trails) {

    }
    global void finish(Database.BatchableContext bc) {

    }
    global List<trailheadapp__Trail__c> start(Database.BatchableContext bc) {
        return null;
    }
}
